apiVersion: v1
kind: Service
metadata: 
   name: customer-service
   labels:
      name: customer-services
      app: project-dayumspec:
   type: LoadBalancer
   ports:
      - port: 80
        targetPort: 80
   selector:
      name: customer-pod
      app: project-dayum
