apiVersion: v1
kind: Service
metadata: 
   name: mongodb
   labels:
      name: mongodb-services
      app: project-dayum

spec:
   ports:
      - port: 27017
        targetPort: 27017
   selector:
      name: mongodb-pod
      app: project-dayum